[test]
# Test configuration for Bun
timeout = "30s"

[install]
# Speed up installations
registry = "https://registry.npmjs.org"
cache = true
frozen = false

[install.scopes]
"@types" = { registry = "https://registry.npmjs.org" }