version: '3.8'

services:
  lens-core:
    build: 
      context: .
      args:
        GIT_SHA: ${GIT_SHA:-unknown}
        BUILD_TIMESTAMP: ${BUILD_TIMESTAMP:-$(date -Iseconds)}
    ports:
      - "50051:50051"
    environment:
      - LENS_MODE=real
      - RUST_LOG=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50051/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./index:/app/index:rw
      
  # Load testing service  
  load-test:
    image: grafana/k6:latest
    depends_on:
      - lens-core
    volumes:
      - ./k6:/scripts
    command: run --out json=/scripts/results.json /scripts/load-test.js