[package]
name = "lens-config"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
config = { workspace = true }
dirs = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }

lens-search-engine = { path = "../search-engine" }
lens-lsp-server = { path = "../lsp-server" }

[dev-dependencies]
tempfile = { workspace = true }
