global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'lens-search'
    static_configs:
      - targets: ['lens:9464']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

rule_files:
  # - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - "alertmanager:9093"