name: Render documentation

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y graphviz
        python -m pip install --upgrade pip
        python -m pip install .[docs]
    - name: Render the documentation
      run: >
        sphinx-build
        -M html ./doc ./build/sphinx
        -T
        -W
        --jobs=auto
        -n
        -vvv
        --keep-going
