version: '3.8'

services:
  # Lightweight test service
  test-web:
    image: nginx:alpine
    ports:
      - "8999:80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Simple JSON service for testing API patterns
  test-api:
    image: python:3.11-slim
    ports:
      - "8998:8000"
    command: >
      bash -c "
        pip install fastapi uvicorn &&
        cat > /app.py << 'EOF'
      from fastapi import FastAPI
      app = FastAPI()
      @app.get('/health')
      def health():
          return {'status': 'ok', 'service': 'test-api'}
      @app.get('/search')
      def search(q: str = 'default'):
          return {'query': q, 'results': [{'path': 'test.py', 'score': 0.9}]}
      EOF
        uvicorn app:app --host 0.0.0.0 --port 8000
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge